apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: pakar
  labels:
    app: keycloak
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: keycloak/keycloak
          args: ["start", "--spi-theme-static-max-age=-1", "--spi-theme-cache-themes=false", "--spi-theme-cache-templates=false"]
env: 
  - name: KEYCLOAK_ADMIN
    valueFrom:
      secretKeyRef:
        name: keycloak-secret
        key: KEYCLOAK_ADMIN
  - name: KEYCLOAK_ADMIN_PASSWORD
    valueFrom:
      secretKeyRef:
        name: keycloak-secret
        key: KEYCLOAK_ADMIN_PASSWORD
  - name: KC_PROXY
    valueFrom:
      secretKeyRef:
        name: keycloak-secret
        key: KC_PROXY
  - name: KC_HOSTNAME
    valueFrom:
      secretKeyRef:
        name: keycloak-secret
        key: KC_HOSTNAME
  - name: KC_DB
    valueFrom:
      secretKeyRef:
        name: keycloak-secret
        key: KC_DB
  - name: KC_DB_URL_HOST
    valueFrom:
      secretKeyRef:
        name: keycloak-secret
        key: KC_DB_URL_HOST
  - name: KC_DB_URL_PORT
    valueFrom:
      secretKeyRef:
        name: keycloak-secret
        key: KC_DB_URL_PORT
  - name: KC_DB_USERNAME
    valueFrom:
      secretKeyRef:
        name: keycloak-secret
        key: KC_DB_USERNAME
  - name: KC_DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: keycloak-secret
        key: KC_DB_PASSWORD
  - name: KC_TRANSACTION_XA_ENABLED
    valueFrom:
      secretKeyRef:
        name: keycloak-secret
        key: KC_TRANSACTION_XA_ENABLED
  - name: KC_HEALTH_ENABLED
    valueFrom:
      secretKeyRef:
        name: keycloak-secret
        key: KC_HEALTH_ENABLED
  - name: KC_DB_URL_PROPERTIES
    valueFrom:
      secretKeyRef:
        name: keycloak-secret
        key: KC_DB_URL_PROPERTIES
          ports:
            - name: http
              containerPort: 8080
          readinessProbe: 
            httpGet:
              scheme: HTTP
              path: /realms/master
              port: 8080
            initialDelaySeconds: 90
            periodSeconds: 10
      volumes: []


---

apiVersion: v1
kind: Service
metadata:
  name: keycloak-svc
  namespace: pakar
  labels:
    app: keycloak
spec:
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
  selector:
    app: keycloak
  type: ClusterIP