apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
  namespace: pakar
type: Opaque
data:
  KEYCLOAK_ADMIN: YWRtaW4=
  KEYCLOAK_ADMIN_PASSWORD: dGVzdDEyMw==
  KC_PROXY: ZWRnZQ==
  KC_HOSTNAME: a2V5LmdrZS1kZXYubGlubm92YXRlLm5ldA==
  KC_DB: cG9zdGdyZXM=
  KC_DB_URL_HOST: cG9zdGdyZXMtc3Zj
  KC_DB_URL_PORT: NTQzMg== 
  KC_DB_USERNAME: cm9ja2V0YWRtaW4=
  KC_DB_PASSWORD: S2V5Y2xvYWsxMiE=
  KC_TRANSACTION_XA_ENABLED: dHJ1ZQ==
  KC_HEALTH_ENABLED: dHJ1ZQ==
  KC_DB_URL_PROPERTIES: P3NzbG1vZGU9ZGlzYWJsZQ==
